### ISSUE TITLE
I think you're calling the function twice here. Could it be?

### ISSUE THREAD

**Issue by Pnlvfx** [pevers/images-scraper#109]
if (Array.isArray(searchQuery)) {
      const promises = searchQuery.map(async (query) => {
        const images = await this._scrapePage(query, limit);
        return { query, images };
      });
      results = await Promise.all(promises);
    } else {
      results = await this._scrapePage(searchQuery, limit);
    }

    await this._scrapePage(searchQuery, limit);

**Comment by pevers** [comment]
> _scrapePage

Seems like it! Thanks for the catch, this makes things faster.
