### ISSUE TITLE
No output with Google Example.

### ISSUE THREAD

**Issue by kikeonline** [pevers/images-scraper#11]
Im getting absolutely no output with the Google Example. Bing works great.

**Comment by pevers** [comment]
Thanks @kikeonline I'll have a look!

**Comment by pevers** [comment]
I can't seem to reproduce this @kikeonline, could you post your package.json file?

**Comment by cimenx** [comment]
i think its related with this https://github.com/segmentio/nightmare/issues/224
when i run it on docker container it doesn't output anything

**Comment by pevers** [comment]
This can be closed as a fix is posted in the related thread:

```sh
DEBUG=nightmare xvfb-run --server-args="-screen 0 1024x768x24" node cnn.js
```
