### ISSUE TITLE
Library No Longer Functions: example no longer returns results

### ISSUE THREAD

**Issue by kanjieater** [pevers/images-scraper#111]
Thanks for the quick release of the 6.4.3 as requested. Unfortunately the reason I'm seeing 0 results wasn't due to that bug, but rather I think the library is no longer functioning as intended. You can see this by running the example code. 

```

var Scraper = require('images-scraper');

const google = new Scraper({
  puppeteer: {
    headless: true,
  },
});

(async () => {
  const results = await google.scrape('banana', 200);
  console.log('results', results);
})();


```
I've used this library for a few years w/o issue and hope to continue using it. Thanks.

**Comment by pevers** [comment]
> Thanks for the quick release of the 6.4.3 as requested. Unfortunately the reason I'm seeing 0 results wasn't due to that bug, but rather I think the library is no longer functioning as intended. You can see this by running the example code.
> 
> ```
> 
> var Scraper = require('images-scraper');
> 
> const google = new Scraper({
>   puppeteer: {
>     headless: true,
>   },
> });
> 
> (async () => {
>   const results = await google.scrape('banana', 200);
>   console.log('results', results);
> })();
> ```
> 
> I've used this library for a few years w/o issue and hope to continue using it. Thanks.

A small bug was introduced but already fixed here: https://github.com/pevers/images-scraper/pull/110 . I just shipped this new release.
