### ISSUE TITLE
Parsing page for image link broken

### ISSUE THREAD

**Issue by Mykybo** [pevers/images-scraper#112]
https://github.com/pevers/images-scraper/blob/2e610717ff970ecd10311fd490ab213cb4f79e5a/src/google/scraper.js#L197

should be changed to "a[href*='/imgres']"

**Comment by pevers** [comment]
@Mykybo you are absolutely right! Not sure how I could have missed this. I'm fixing it!

**Comment by pevers** [comment]
Thanks for letting me know

**Comment by pevers** [comment]
I published a new release, should be fixed now. Thanks!
