### ISSUE TITLE
google.on('result', cb) not working

### ISSUE THREAD

**Issue by cimenx** [pevers/images-scraper#15]
try to listening event 'result'
```javascript
var google = new Scraper.Google()
google.list({
	keyword: 'banana',
	num: 10
})

google.on('result', function(item) {
	console.log('result', item);
});
```
it doesn't 
output anything
But when i try using bing it give me the result (from bing of course)
```javascript
var bing = new Scraper.Bing()
bing.list({
	keyword: 'banana',
	num: 10
})

bing.on('result', function(item) {
	console.log('result', item);
});
```

**Comment by gideonjones** [comment]
I'm replicating this - not an issue for me as bing sufficient for my needs but just chiming in.

**Comment by pevers** [comment]
@cimenx Can you see what's happening when you enable the 'show: true' parameter? Maybe something is going on with Electron.

**Comment by pevers** [comment]
I'm wondering if this can be caused by a fresh Electron instance without cache. The first time it uses Google a 'Accept the policy' window appear that can possibly prevent the search.

**Comment by pevers** [comment]
Or it can be related to this:
https://github.com/pevers/images-scraper/issues/11

If you are running this in a server environment
