### ISSUE TITLE
Is there a way to prevent the Google image scraper from scrolling down and loading tons of images?

### ISSUE THREAD

**Issue by ghubcompressedtime** [pevers/images-scraper#19]
It takes a long time and I only want to load the first ten or so images in any case.

Thank you.

**Comment by pevers** [comment]
Hi @ghubcompressedtime,

It is possible, I would however change the code by removing the Nightmare headless browser and switch to a simple Request call that fetches the first page of Google images. That is beyond this project but I can try to come up with an early opt-out option that stops scrolling as soon as it hits x results.

**Comment by ramazan793** [comment]
So, you did it?

**Comment by pevers** [comment]
I have finally fixed this.
