### ISSUE TITLE
No result.

### ISSUE THREAD

**Issue by azarus** [pevers/images-scraper#20]
Not working?
```
var Scraper = require('google-images-scraper');
 
var scraper = new Scraper({
    keyword: 'banana',
    rlimit: 10  // 10 p second 
});
 
scraper.list(10).then(function (res) {
    console.log(res);
}).catch(function(err)
{
  console.log(err);
});
```
The output:
```
[ undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined ]
```

Also no errors?
What am i doing wrong?

**Comment by azarus** [comment]
Oh looks like its a different or older project on npm:
https://www.npmjs.com/package/google-images-scraper

Please do something about its ince its the first one i found on google :D

Installed the correct package and now works like charm 💃

**Comment by pevers** [comment]
Thanks! Ill fix it, this is indeed an old version.
