### ISSUE TITLE
Limit reached 

### ISSUE THREAD

**Issue by Mwea** [pevers/images-scraper#21]
Hi ! 

I just tried your code but; it seems to be limited to only 600 images per scrapper, is it normal ? 
```
var Scraper = require('images-scraper'), google = new Scraper.Google();
['banana', 'apple', 'cherry'].map(category => {
    google
        .list({
            keyword: category,
            num: 5000,
            detail: true,
            nightmare: {
                show: true
            }
        }).then(function (res) {
        console.log('first 10000 results from google', res.length);
    })
        .catch(function (err) {
            console.log('err', err);
        })
});
```

**Comment by pevers** [comment]
Hi @Mwea , it is possible because Google will not always show 1000 results I believe. The scraper will scroll through the page and fetch as much results as possible.

**Comment by Mwea** [comment]
Hi !  @pevers 
I just saw that the scrapper stop to get data when it sees the "show more results" link of google, 
this could be great if the code was able to "click" on this button and keep downloading. 
:+1:

**Comment by pevers** [comment]
It is doing that. Closing it.
