### ISSUE TITLE
Output gets 'Truncated' 

### ISSUE THREAD

**Issue by ExpatRights** [pevers/images-scraper#27]
Everytime I run this in Windows Powershell command line  "node bing-images-scraper-2.js" with 100+ items, the output gets 'truncated'. I tried using > to output to a file, I try editing Powershell settings, etc. The output gets 'truncated' and ends at line ~700 with:

  ... 224 more items ]

Just using the basic Bing scraper provided by Pevers. Help?!

**Comment by pevers** [comment]
I think the console.log is truncating the response since a new Node version.

Try logging it as:

```nodejs
require("util").inspect.defaultOptions.maxArrayLength = null
console.log(obj)
```
Or write it directly to a file using fs.

**Comment by ExpatRights** [comment]
Thanks! I got a redditor to help too, it's a console.log issue.
