### ISSUE TITLE
Not working on Heroku 

### ISSUE THREAD

**Issue by Manish-Mehta** [pevers/images-scraper#29]
Not returning anything while scrapping from Google on Heroku platform.
images are scraped finely in my local environment, but when code is deployed in Heroku nothing is happening no error no result from promise.

**Comment by aayushsinghm16** [comment]
same here, It doesn't work

**Comment by sungkuk5420** [comment]
I am using a translator.

This is a problem in which Nightmare does not work in Linux.

I found your answer on the link below.

https://stackoverflow.com/questions/34795037/nightmare-js-not-working-as-expected-on-ubuntu-linux-cloud-server

>I'm just posting this for posterity.
Below is the bash script to install nightmarejs with node (4.2.4) on a clean Ubuntu Linux machine. I've tested this on a DigitalOcean droplet running 14.04.

```
Apt-get-y update
Apt-get-Y Upgrade
Apt-get-y -- force - make the in-grow tk- ++ li- cy fb bg - - sl- il xk- bil ts- ononts xfonts - 100 100onts - 75 xfon onon ts
Mkdir src
Cd src
Wget https://nodejs.org/dist/v4.2.4/node-v4.2.4.tar.gz
Tar xzf node- v4.2.4.tar. gz
Cd node- v.2.4
. / Configuration
Make - j 2
Make install
CD ..
Mkdir nightmarejs
Cd nightmarejs
Npm-f init
Npm install -- save nightmare voltage
```

> Then you simply create the .js file (e.g. hello_nightmare.js) (in the same directory where nightmarejs is installed) and then run it using the command below (as already mentioned in @yoz's answer):

`xv fb-run node-harmony hello _ nightmare.js.`

good luck!
