### ISSUE TITLE
update package versions

### ISSUE THREAD

**Issue by perpetualchaos** [pevers/images-scraper#34]
Please upgrade the following, it should remedy the following issues

- nightmare@3.0.2 https://electronjs.org/blog/filereader-fix#mitigation
- cheerio@1.0.0-rc.3 https://github.com/lodash/lodash/issues/3359
- lodash@4.17.12 https://github.com/lodash/lodash/issues/3359
- validator@5.0.0 https://github.com/validatorjs/validator.js/issues/502

**Comment by pevers** [comment]
Thanks @perpetualchaos ! I will try to update this shortly

**Comment by pevers** [comment]
Everything is done. Thanks!
