### ISSUE TITLE
advanced option for 'Usage rights' filter?

### ISSUE THREAD

**Issue by wutayng** [pevers/images-scraper#40]
Is there an appropriate filter for 'Usage rights' options on Google Image Search similar to the options below: ?

```javascript
advanced: {
      imgType: 'photo', // options: clipart, face, lineart, news, photo
      resolution: 'l', // options: l(arge), m(edium), i(cons), etc.
      color: undefined // options: color, gray, trans
  }
```

**Comment by pevers** [comment]
Yes there is: https://github.com/pevers/images-scraper/pull/39

I added a general option field to pass down as query parameters. In the last update you can do:
`tbs: { sur: "fc" // commercial reuse }` for example
