### ISSUE TITLE
Unable to scrape URLs more than 100

### ISSUE THREAD

**Issue by pkhigh** [pevers/images-scraper#45]
Hi, 
I have attached the console output whenever I try to input the limit more than 100.
![Screenshot 2020-04-11 at 3 22 48 AM](https://user-images.githubusercontent.com/34805449/79038007-fb0c6280-7ba3-11ea-9a61-ab692a0def34.png)

**Comment by pevers** [comment]
Hi @pkhigh 

I don't really understand the issue. How many results did you get? What was the limit? Is it possible that you didn't get more because there are none?

**Comment by pkhigh** [comment]
It was an issue with console output limit. I solved it by changing the maxArrayLenght console to None. By default it was set to 100.
