### ISSUE TITLE
I set 300 but scraper is only getting 200 images.

### ISSUE THREAD

**Issue by ledlamp** [pevers/images-scraper#46]
```js
var gi = new GIScraper({ puppeteer: { headless: false } });
let results = await gi.scrape("melony pokemon", 300);
console.log(`${results.length} results`);
```
It's always 200.

**Comment by diornister** [comment]
basically on file images-scraper/src/google/scraper.js, line 64 there is a mistake, 
results = links.slice(0, limit - results.length);
should be 
results = links.slice(0, limit);

if the owner give me permission i could make a pr to fix this.

**Comment by ledlamp** [comment]
Can't anyone open pull requests?

**Comment by diornister** [comment]
> Can't anyone open pull requests?

he needs to give permission for this.

**Comment by diornister** [comment]
But as a fix, you can set your limit to double of what you want, and it will fetch you more images.

**Comment by ledlamp** [comment]
https://github.com/pevers/images-scraper/blob/8cef8c8b5f3459eda60558080515df84803d4143/src/google/scraper.js#L56-L71

It looks to me like `results = links.slice(0, limit - results.length);` should be `results.concat(links);` and `results = results.slice(0, limit - results.length);` should be added after the while loop.

**Comment by ledlamp** [comment]
Or wait no, HTML will have all the images in it. 🤔

**Comment by ledlamp** [comment]
Ah yes I think you're right; `limit - results.length` would work if the number of results is greater than the limit, then it gets a negative number to slice back from. But when it's less (say 100 results) and limit is 300... wait then it won't do anything...
Hmm I think either way it'll do the same thing; both `.slice(0, 300 - 100 )` and `.slice(0, 300)` will not change the 100 long array, and `.slice(0, 300-400)` will do the same as `.slice(0, 300)` for a 400 long array.
I think the issue is somewhere else, maybe the thing that decides when the end has been reached.

**Comment by pevers** [comment]
Everyone should be able to fork it and create a pull request.

But there is indeed a mistake here @ledlamp . Sorry, I have fixed it here: https://github.com/pevers/images-scraper/pull/47
