### ISSUE TITLE
Google result count maxes out at 100, 200, or 300

### ISSUE THREAD

**Issue by jaredscheib** [pevers/images-scraper#5]
hey @pevers, thoughts on this by chance?

If I try to get 1000 images, it will only return 100, 200, or 300. I think it has to do with the scrolling emulation and the timeout built into this mechanism.

About to dive back in to see how to get 1000 or more images at a time.

**Comment by pevers** [comment]
@jaredscheib Thanks for reporting, the Google scraper is really tricky and it is hard to get it robust. I'll have a look into it asap (really busy at the moment).

**Comment by jaredscheib** [comment]
Gotcha - thanks. Maybe I'll just switch over to Bing, Yahoo, & Picsearch. Something about brand-loyalty kept me on Google :)

**Comment by TimZaman** [comment]
+1; Did you look into this @pevers ?

**Comment by pevers** [comment]
@TimZaman not yet, I'll try to fix it this weekend.

**Comment by pevers** [comment]
Fixed the issue, cleaned up a lot of unneeded code. Seems to be working again, sorry for the delay @TimZaman and @jaredscheib

**Comment by jaredscheib** [comment]
Thanks @pevers!
