### ISSUE TITLE
Error on heroku

### ISSUE THREAD

**Issue by WhoIAm451** [pevers/images-scraper#55]
When i use the images-scraper api on heroku i have this error :
Error: Failed to launch the browser process!

**Comment by feroci1024** [comment]
You must install https://elements.heroku.com/buildpacks/jontewks/puppeteer-heroku-buildpack
and also, set this in CLI
`npm config set puppeteer_download_host=https://npm.taobao.org/mirrors`
then, reinstall puppeteer

**Comment by pevers** [comment]
Thanks @feroci1024 ! Closing this and adding it to the README.
