### ISSUE TITLE
Repl.it: Failed at the puppeteer@2.1.1 install script

### ISSUE THREAD

**Issue by jaydenkoh** [pevers/images-scraper#56]
I tried to install and it just said failed to install at the puppeteer

**Comment by pevers** [comment]
Thanks for reporting @jaydenkoh . Can you try again with the latest version? I upgraded all dependencies.

**Comment by pevers** [comment]
Hi @jaydenkoh . Sorry for the late response.

I created an example repl.it, you should use a bash repl instead of a NodeJS repl. 

Example: https://repl.it/join/hylyxvxc-peterevers
