### ISSUE TITLE
Repl.it: failed to install images-scraper

### ISSUE THREAD

**Issue by davi-fonto** [pevers/images-scraper#59]
Hi, i tried to download your package into a new project on repl and it doesn't work. Can you please fix it? :)

**Comment by pevers** [comment]
Hi @davi-fonto , can you please provide a bit of context? 

What did you try, what is the output and what doesn't work?

**Comment by davi-fonto** [comment]
![issue](https://user-images.githubusercontent.com/76854811/105769214-c6fd0500-5f5d-11eb-9c5e-407df08e76db.png)
that's the error i see into the repl console

**Comment by pevers** [comment]
Hi @davi-fonto , sorry for the late response.

You should use a bash repl instead of a nodejs repl.

Example: https://repl.it/join/hylyxvxc-peterevers
