### ISSUE TITLE
"Failed to launch the browser process" on Ubuntu

### ISSUE THREAD

**Issue by SpeckyYT** [pevers/images-scraper#62]
When trying to scrape images from my Ubuntu machine, I get the following error:
```
Error: Failed to launch the browser process!
[0220/172827.691150:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

**Comment by pevers** [comment]
Hi @SpeckyYT  , sorry for the late response.

You should use a bash repl instead of a nodejs repl.

Example: https://repl.it/join/hylyxvxc-peterevers

**Comment by SpeckyYT** [comment]
I never used repl in my life.
I have an Ubuntu Machiene.

**Comment by pevers** [comment]
Woops, I was a little to enthousiastic closing issues.

Do you pass any options? 

```
{args: ['--no-sandbox', '--disable-setuid-sandbox']}
```

Will not work as root user. So you should either remove that or run it as non-root user

**Comment by SpeckyYT** [comment]
it works correctly now, thanks.
