### ISSUE TITLE
Failed to boot on Meteor v1.3+React app

### ISSUE THREAD

**Issue by ferroariel** [pevers/images-scraper#7]
App fails to boot , error is following

```
Administrador@IT65441 C:\wamp\www\mskeor-react
$ meteor
[[[[[ C:\wamp\www\mskeor-react ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Meteor 1.3.2.4 is available. Update this project with 'meteor update'.
W20160425-17:45:55.558(-3)? (STDERR)
W20160425-17:45:55.559(-3)? (STDERR) packages\modules.js:74364
W20160425-17:45:55.559(-3)? (STDERR)   this.proc.stdout.pipe(split2()).on('data', (data) => {
W20160425-17:45:55.559(-3)? (STDERR)                                                      ^
W20160425-17:45:55.559(-3)? (STDERR) SyntaxError: Unexpected token >
W20160425-17:45:55.560(-3)? (STDERR)     at C:\wamp\www\mskeor-react\.meteor\local\build\programs\server\boot.js:278:30
W20160425-17:45:55.560(-3)? (STDERR)     at Array.forEach (native)
W20160425-17:45:55.560(-3)? (STDERR)     at Function._.each._.forEach (C:\Users\Administrador\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160425-17:45:55.560(-3)? (STDERR)     at C:\wamp\www\mskeor-react\.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 8
W20160425-17:46:02.312(-3)? (STDERR)
W20160425-17:46:02.312(-3)? (STDERR) packages\modules.js:74364
W20160425-17:46:02.312(-3)? (STDERR)   this.proc.stdout.pipe(split2()).on('data', (data) => {
W20160425-17:46:02.312(-3)? (STDERR)                                                      ^
W20160425-17:46:02.312(-3)? (STDERR) SyntaxError: Unexpected token >
W20160425-17:46:02.313(-3)? (STDERR)     at C:\wamp\www\mskeor-react\.meteor\local\build\programs\server\boot.js:278:30
W20160425-17:46:02.313(-3)? (STDERR)     at Array.forEach (native)
W20160425-17:46:02.313(-3)? (STDERR)     at Function._.each._.forEach (C:\Users\Administrador\AppData\Local\.meteor\packages\meteor-tool\1.3.1\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\underscore\underscore.js:79:11)
W20160425-17:46:02.313(-3)? (STDERR)     at C:\wamp\www\mskeor-react\.meteor\local\build\programs\server\boot.js:133:5
=> Exited with code: 8
```

**Comment by pevers** [comment]
I don't think this is related to images-scraper @ferroariel ?

**Comment by ferroariel** [comment]
I´ve installed this package on a Meteor Blaze based project with success.
Now, when trying to do the very same on a React based app, this error is being thrown, and due to the fact that the project uses several packages and works OK, this thing has to be related to this package in some way
I´ll let you know if I can find something on my behalf

**Comment by pevers** [comment]
@ferroariel Looks like there is no support for ECMAScript 6. Maybe it is using an old version of Node where ECMA6 was not on for default?

**Comment by ferroariel** [comment]
Local Node is v4.4.2

On Tue, Apr 26, 2016 at 11:07 AM, Peter Evers <notifications@github.com>
wrote:

> @ferroariel <https://github.com/ferroariel> Looks like there is no
> support for ECMAScript 6. Maybe it is using an old version of Node where
> ECMA6 was not on for default?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pevers/images-scraper/issues/7#issuecomment-214757012>
>



-- 
Saludos,

*Ariel Ferro*
*Cel*: (011) 15 6614 7084

www.alegoriaweb.com <http://www.satela.com.ar/>
Diseño Web Multiplataforma

**Comment by devcollectief** [comment]
@ferroariel can you dump your `package.json` && `bower.json` here as well as the node version you are using on that windows machine and the windows version?

**Comment by ferroariel** [comment]
​Node v
​4.4.2

[​package.json]​
​
​
​{
  "name": "mskeor-react",
  "private": true,
  "scripts": {
    "start": "meteor run"
  },
  "dependencies": {
    "core-js": "^2.2.2",
    "domready": "^1.0.8",
    "fbjs": "^0.8.0",
    "images-scraper": "^2.0.9",
    "meteor-node-stubs": "^0.2.3",
    "object-assign": "^4.0.1",
    "react": "^15.0.1",
    "react-addons-css-transition-group": "^15.0.1",
    "react-addons-pure-render-mixin": "^15.0.1",
    "react-addons-transition-group": "^15.0.1",
    "react-dom": "^15.0.1",
    "react-mixin": "^3.0.5",
    "react-mounter": "^1.2.0",
    "request": "^2.71.0",
    "underscore.string": "^3.3.4"
  },
  "version": "1.0.0",
  "main": "startUpServer.js",
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}

>> no bower.json!
​



On Tue, May 3, 2016 at 4:02 AM, Tim Kock <notifications@github.com> wrote:

> @ferroariel <https://github.com/ferroariel> can you dump your package.json
> && bower.json here as well as the node version you are using on that
> windows machine and the windows version?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/pevers/images-scraper/issues/7#issuecomment-216454431>
>



-- 
Saludos,

*Ariel Ferro*
*Cel*: (011) 15 6614 7084

www.alegoriaweb.com <http://www.satela.com.ar/>
Diseño Web Multiplataforma
