### ISSUE TITLE
Only Sending One Image

### ISSUE THREAD

**Issue by Neehaw** [pevers/images-scraper#70]
So I implemented this into a discord bot, and its only sending the same image, even after adding 200 after the search query in the code. How can I fix this?

**Comment by MarceloBrazolim** [comment]
It returns the json's in the order it appears in the web, you have to manually shuffle the resuls. I preffer the npm lodash to do so. but you can randomize it anyway you like.

```js
const { shuffle } = require("lodash");
const result = shuffle(await google.scrape(query, 40));
```

**Comment by pevers** [comment]
Thanks for taking care of this @MarceloBrazolim . I think this can be closed.
