### ISSUE TITLE
Add a filter for nsfw words

### ISSUE THREAD

**Issue by imranbarbhuiya** [pevers/images-scraper#78]
Add a filter for nsfw words. Also if it is safe mode then please give an example that where should i use the options.

**Comment by pevers** [comment]
Hey @imranbarbhuiya , you can use the 'safe' option in the constructor.

```js
const google = new Scraper({
  puppeteer: {
    safe: true
  },
});
```

**Comment by imranbarbhuiya** [comment]
Ty got it

**Comment by imranbarbhuiya** [comment]
hey what this option does? i tought it will filter nsfw images but it isn't doing that.

**Comment by imranbarbhuiya** [comment]
I've tried like this but it isn't working.
var Scraper = require("images-scraper");
const google = new Scraper({
  puppeteer: {
    safe: true,
    headless: true,
  },
});

**Comment by MarceloBrazolim** [comment]
> 
> 
> hey what this option does? i tought it will filter nsfw images but it isn't doing that.

this option uses the safe search feature from google, it's the same as turning it on on your browser.
the google safe search feature tries to filter off contents that google understands as NSFW with an artificial intelligence, so it may not be 100% safe after all.
