### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by Bigby331** [pevers/images-scraper#84]
**When I do a research :** 
  const google      = new Scraper({
      puppeteer: {
          executablePath: '/usr/bin/chromium-browser',
          timeout: 0,
          waitUntil: 'load'
      },
  });
  
  const results = await google.scrape(`banane`,  5);

**I have this error :** 

  /node_modules/images-scraper/node_modules/puppeteer/lib/cjs/puppeteer/common/LifecycleWatcher.js:106
          return new Promise((fulfill) => (this._maximumTimer = setTimeout(fulfill, this._timeout))).then(() => new Errors_js_1.TimeoutError(errorMessage));
                                                                                                                ^
  
  TimeoutError: Navigation timeout of 30000 ms exceeded

**If somebody can help me please**

**Comment by MarceloBrazolim** [comment]
{4,0} > timeout: 0,

if i'm not mistaken the error given is because you're requesting for a timeout of 0ms, wich is nearly impossible, try increasing this number or removing the constructor option.
