### ISSUE TITLE
The "url" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by nitsanasraf** [pevers/images-scraper#88]
I am trying to scrape a bunch of categories, and after like 3 images, I get this error and it stops the agent from scraping more.

It does work when I don't use many categories, and for some queries, it works, so overall not stable at all for some reason.

That's my code:

```
const Scraper = require("images-scraper");

const google = new Scraper({
  puppeteer: {
    headless: false,
  },
});

const categories = ["shark", "cat", "lion", "snake", "spider"];

(async () => {
  try {
    const results = await google.scrape(categories, 10);
    results.forEach((item, index) => {
      item.images.forEach((img, i) => {
        //do something with images
      });
    });
  } catch (e) {
    console.log("Scraping failed", e);
  }
})();

```

**Comment by Glutius** [comment]
I get this issue from time to time too. Any progress?

**Comment by pevers** [comment]
Sorry I can't really reproduce it. Can you provide an OS and version? Can you also describe what happens when it doesn't work?

**Comment by ulnk** [comment]
![image](https://user-images.githubusercontent.com/93608862/205375181-e58717d0-450f-4e6e-bc8e-ed58ee7369ea.png)
its random

**Comment by EliuTimana** [comment]
I got the same error, and I fixed that here [https://github.com/pevers/images-scraper/pull/107](https://github.com/pevers/images-scraper/pull/107)

**Comment by Dharmendra016** [comment]
I also got the same issue

**Comment by kanjieater** [comment]
@pevers can we get an npm release for the fix?

**Comment by pevers** [comment]
> @pevers can we get an npm release for the fix?

I just did the release. Thanks for reminding me and sorry for the delay
